# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 15562071937c0ae70ce1ed4cd8eb90227dd4520c48400825ae6ea6055f79aa319512ebc7bcd8fd3f4d971fbc2fb82768c89fef69e2af4df133aa7412c9e10987

test:
  secret_key_base: 82327d43443bf0ec2faa95b0319da4ce3f1694ee9a3a221917990f2215ce94e4585b90d565dcd84057319cdb49a3a68b77fafe1e24d0f1d09ca4ed6faa049eb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
